services:
  db:
    image: postgres:16.4-alpine3.20
    container_name: postgres-db
    env_file:
      - ../.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5438:5432"
    networks:
      - app-network
    
networks:
  app-network:

volumes:
  postgres_data: