"""empty message

Revision ID: 15019ec30eda
Revises: 92fa9575626e
Create Date: 2024-10-11 15:30:05.515024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15019ec30eda'
down_revision: Union[str, None] = '92fa9575626e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('engineer_personal_personal_category_id_fkey', 'engineer_personal', type_='foreignkey')
    op.create_foreign_key(None, 'engineer_personal', 'personal_category', ['personal_category_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('personal_workers_personal_category_id_fkey', 'personal_workers', type_='foreignkey')
    op.create_foreign_key(None, 'personal_workers', 'personal_category', ['personal_category_id'], ['id'], ondelete='CASCADE')
    op.alter_column('product', 'laboratory_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('tools_laboratory_id_fkey', 'tools', type_='foreignkey')
    op.create_foreign_key(None, 'tools', 'test_laboratories', ['laboratory_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('works_with_product_product_id_fkey', 'works_with_product', type_='foreignkey')
    op.create_foreign_key(None, 'works_with_product', 'product', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('workshop_product_category_id_fkey', 'workshop', type_='foreignkey')
    op.create_foreign_key(None, 'workshop', 'product_category', ['product_category_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workshop', type_='foreignkey')
    op.create_foreign_key('workshop_product_category_id_fkey', 'workshop', 'product_category', ['product_category_id'], ['id'])
    op.drop_constraint(None, 'works_with_product', type_='foreignkey')
    op.create_foreign_key('works_with_product_product_id_fkey', 'works_with_product', 'product', ['product_id'], ['id'])
    op.drop_constraint(None, 'tools', type_='foreignkey')
    op.create_foreign_key('tools_laboratory_id_fkey', 'tools', 'test_laboratories', ['laboratory_id'], ['id'])
    op.alter_column('product', 'laboratory_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'personal_workers', type_='foreignkey')
    op.create_foreign_key('personal_workers_personal_category_id_fkey', 'personal_workers', 'personal_category', ['personal_category_id'], ['id'])
    op.drop_constraint(None, 'engineer_personal', type_='foreignkey')
    op.create_foreign_key('engineer_personal_personal_category_id_fkey', 'engineer_personal', 'personal_category', ['personal_category_id'], ['id'])
    # ### end Alembic commands ###
