"""empty message

Revision ID: 92fa9575626e
Revises: 2e831fb9430f
Create Date: 2024-10-11 14:57:12.211808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '92fa9575626e'
down_revision: Union[str, None] = '2e831fb9430f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('brigades_product_id_fkey', 'brigades', type_='foreignkey')
    op.drop_constraint('brigades_workshop_id_fkey', 'brigades', type_='foreignkey')
    op.create_foreign_key(None, 'brigades', 'workshop', ['workshop_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'brigades', 'product', ['product_id'], ['id'], ondelete='CASCADE')
    op.alter_column('product', 'process_finish',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'process_finish',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.drop_constraint(None, 'brigades', type_='foreignkey')
    op.drop_constraint(None, 'brigades', type_='foreignkey')
    op.create_foreign_key('brigades_workshop_id_fkey', 'brigades', 'workshop', ['workshop_id'], ['id'])
    op.create_foreign_key('brigades_product_id_fkey', 'brigades', 'product', ['product_id'], ['id'])
    # ### end Alembic commands ###
